### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by poneill00** [Cascading/vagrant-cascading-hadoop-cluster#13]
Getting the following error when running against Cascading 2.6.1 and 2.5.5

The class/method not found is under hadoop-yarn-common-2.2.0.jar

2014-12-19 15:23:24,588 INFO [main] org.apache.hadoop.http.HttpServer: Added global filter 'safety' (class=org.apache.hadoop.http.HttpServer$QuotingInputFilter)
2014-12-19 15:23:24,592 FATAL [main] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: Error starting MRAppMaster
java.lang.NoSuchMethodError: org.apache.hadoop.yarn.webapp.util.WebAppUtils.getProxyHostsAndPortsForAmFilter(Lorg/apache/hadoop/conf/Configuration;)Ljava/util/List;
    at org.apache.hadoop.yarn.server.webproxy.amfilter.AmFilterInitializer.initFilter(AmFilterInitializer.java:40)
    at org.apache.hadoop.http.HttpServer.<init>(HttpServer.java:272)
    at org.apache.hadoop.yarn.webapp.WebApps$Builder$2.<init>(WebApps.java:222)
    at org.apache.hadoop.yarn.webapp.WebApps$Builder.start(WebApps.java:219)
    at org.apache.hadoop.mapreduce.v2.app.client.MRClientService.serviceStart(MRClientService.java:136)
    at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
    at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.serviceStart(MRAppMaster.java:1058)
    at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
    at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$1.run(MRAppMaster.java:1445)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:416)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
    at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.initAndStartAppMaster(MRAppMaster.java:1441)
    at org.apache.hadoop.mapreduce.v2.app.MRAppMaster.main(MRAppMaster.java:1374)
2014-12-19 15:23:24,603 INFO [Thread-1] org.apache.hadoop.mapreduce.v2.app.MRAppMaster: MRAppMaster received a signal. Signaling RMCommunicator and JobHistoryEventHandler.
2014-12-19 15:23:24,603 WARN [Thread-1] org.apache.hadoop.util.ShutdownHookManager: ShutdownHook 'MRAppMasterShutdownHook' failed, java.lang.NullPointerException
java.lang.NullPointerException
    at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$ContainerAllocatorRouter.setSignalled(MRAppMaster.java:827)
    at org.apache.hadoop.mapreduce.v2.app.MRAppMaster$MRAppMasterShutdownHook.run(MRAppMaster.java:1395)
    at org.apache.hadoop.util.ShutdownHookManager$1.run(ShutdownHookManager.java:54)

**Comment by fs111** [comment]
I am not completely following. What exactly are you doing? Are you using the distributed cluster or the single node option? How are you submitting your job and how is the job jar being build?

 "hadoop-yarn-common-2.2.0.jar" <- looks like your job jar contains the hadoop jars, which it should not. The cluster is on 2.5.2, so there should be no mention of 2.2.0 cluster side.

**Comment by poneill00** [comment]
hey,

running the distributed cluster, 3 hadoop nodes and a master.

I'm building a fat jar and running as hadoop jar, no classpath.

It looks like the 2.2.0 dependency is coming from the cascading-hbase-hadoop2-mr1 jar, I removed this dependency (and my hbase taps) and the errors go away.

Thanks for replying.

Looks similar to this:
https://groups.google.com/forum/#!msg/cascading-user/_fHwHb8Acz8/GYWPYT2Ar-0J

**Comment by poneill00** [comment]
Just spotted I had cascading-hadoop rather than hadoop2-mr1 as dependency....confirming thats the issue now... :(

**Comment by poneill00** [comment]
Unfortunately thats not fixing it either

I'll open something against cascading-hbase

[INFO] +- cascading-hbase:cascading-hbase-hadoop2-mr1:jar:2.6.0:compile
[INFO] |  +- xerces:xercesImpl:jar:2.9.1:compile
[INFO] |  |  - xml-apis:xml-apis:jar:1.3.04:compile
[INFO] |  +- org.apache.hbase:hbase-server:jar:0.98.6.1-hadoop2:compile
[INFO] |  |  +- org.apache.hbase:hbase-protocol:jar:0.98.6.1-hadoop2:compile
[INFO] |  |  +- org.apache.hbase:hbase-prefix-tree:jar:0.98.6.1-hadoop2:runtime
[INFO] |  |  |  - org.apache.hbase:hbase-common:jar:tests:0.98.6.1-hadoop2:runtime
......
......
[INFO] |  |  +- org.apache.hadoop:hadoop-common:jar:2.2.0:compile
[INFO] |  |  |  +- xmlenc:xmlenc:jar:0.52:compile
[INFO] |  |  |  +- commons-net:commons-net:jar:3.1:compile
[INFO] |  |  |  +- net.java.dev.jets3t:jets3t:jar:0.6.1:compile
[INFO] |  |  |  +- commons-configuration:commons-configuration:jar:1.6:compile
[INFO] |  |  |  |  +- commons-digester:commons-digester:jar:1.8:compile
[INFO] |  |  |  |  |  - commons-beanutils:commons-beanutils:jar:1.7.0:compile
[INFO] |  |  |  |  - commons-beanutils:commons-beanutils-core:jar:1.8.0:compile
[INFO] |  |  |  - com.jcraft:jsch:jar:0.1.42:compile
[INFO] |  |  +- org.apache.hadoop:hadoop-auth:jar:2.2.0:compile
[INFO] |  |  +- org.apache.hadoop:hadoop-client:jar:2.2.0:compile
[INFO] |  |  |  +- org.apache.hadoop:hadoop-mapreduce-client-app:jar:2.2.0:compile
[INFO] |  |  |  |  +- org.apache.hadoop:hadoop-mapreduce-client-common:jar:2.2.0:compile
[INFO] |  |  |  |  |  +- org.apache.hadoop:hadoop-yarn-client:jar:2.2.0:compile
[INFO] |  |  |  |  |  - org.apache.hadoop:hadoop-yarn-server-common:jar:2.2.0:compile
[INFO] |  |  |  |  - org.apache.hadoop:hadoop-mapreduce-client-shuffle:jar:2.2.0:compile
[INFO] |  |  |  +- org.apache.hadoop:hadoop-yarn-api:jar:2.2.0:compile
[INFO] |  |  |  - org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:2.2.0:compile
[INFO] |  |  +- org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.2.0:compile
[INFO] |  |  |  +- org.apache.hadoop:hadoop-yarn-common:jar:2.2.0:compile

**Comment by fs111** [comment]
Closing this one. Handling the problem in https://github.com/Cascading/cascading.hbase/issues/7
